const API_GATEWAY = "https://d5dkffis8kfdsr7g6rjo.z7jmlavt.apigw.yandexcloud.net";

export const FUNCTIONS = {
  "upload-photo": `${API_GATEWAY}/generate-upload-url`,
  "generate-upload-url": `${API_GATEWAY}/generate-upload-url`,
  "update-activity": `${API_GATEWAY}/update-activity`,
  "blacklist": `${API_GATEWAY}/blacklist`,
  "get-subscriptions": `${API_GATEWAY}/get-subscriptions`,
  "subscribe": `${API_GATEWAY}/subscribe`,
  "profile-photos": `${API_GATEWAY}/profile-photos`,
  "get-conversations": `${API_GATEWAY}/get-conversations`,
  "private-messages": `${API_GATEWAY}/private-messages`,
  "payment-webhook": `${API_GATEWAY}/payment-webhook`,
  "create-payment": `${API_GATEWAY}/create-payment`,
  "add-energy": `${API_GATEWAY}/add-energy`,
  "register": `${API_GATEWAY}/register`,
  "reset-password": `${API_GATEWAY}/reset-password`,
  "login": `${API_GATEWAY}/login`,
  "add-reaction": `${API_GATEWAY}/add-reaction`,
  "get-user": `${API_GATEWAY}/get-user`,
  "create-user": `${API_GATEWAY}/create-user`,
  "admin-users": `${API_GATEWAY}/admin-users`,
  "get-messages": `${API_GATEWAY}/get-messages`,
  "send-message": `${API_GATEWAY}/send-message`,
  "verify-sms": `${API_GATEWAY}/verify-sms`,
  "send-sms": `${API_GATEWAY}/send-sms`,
  "geocode": "https://functions.poehali.dev/90e9cacc-48ca-4b42-b817-3a77b67db25c",
  "update-location": "https://functions.poehali.dev/1e164728-c695-4c1a-9496-29af61259212",
} as const;