export const FUNCTIONS = {
  "upload-photo": "https://functions.yandexcloud.net/d4e1drh1ub4imqleg10q",
  "generate-upload-url": "https://functions.yandexcloud.net/d4e1drh1ub4imqleg10q",
  "update-activity": "https://functions.yandexcloud.net/d4es73t1cfkmee0kd724",
  "blacklist": "https://functions.yandexcloud.net/d4enost4267cmd15cnf1",
  "get-subscriptions": "https://functions.yandexcloud.net/d4eaga56gmoe21os17od",
  "subscribe": "https://functions.yandexcloud.net/d4eruja65h9305n21its",
  "profile-photos": "https://functions.yandexcloud.net/d4emmve89ihd1nnfhcm9",
  "get-conversations": "https://functions.yandexcloud.net/d4ebuvvtbpqd5f09070g",
  "private-messages": "https://functions.yandexcloud.net/d4es8snba4ua5e0s6kgr",
  "payment-webhook": "https://functions.yandexcloud.net/d4e235nr619fsgkt1qvi",
  "create-payment": "https://functions.yandexcloud.net/d4e1gbggnqgt6lrsh9n7",
  "add-energy": "https://functions.yandexcloud.net/d4e10cfpm08ikk1k5mp4",
  "register": "https://functions.yandexcloud.net/d4erd2o6kv7rjhsb9a9h",
  "reset-password": "https://functions.yandexcloud.net/d4ek1ma9n1s3m5150jhb",
  "login": "https://functions.yandexcloud.net/d4eae7r2eq6bt0ucrv35",
  "add-reaction": "https://functions.yandexcloud.net/d4e1u813mmf6jpgb1581",
  "get-user": "https://functions.yandexcloud.net/d4ev53geag7ku6b1dvpj",
  "create-user": "https://functions.yandexcloud.net/d4egbht42po268s1q56a",
  "admin-users": "https://functions.yandexcloud.net/d4ev3dr7fqpjpd9p24ma",
  "get-messages": "https://functions.yandexcloud.net/d4e25ugin6o29hr4ots8",
  "send-message": "https://functions.yandexcloud.net/d4eqjhv1ab66or71e1i4",
  "verify-sms": "https://functions.yandexcloud.net/d4egj9hb0n3psc0eck02",
  "send-sms": "https://functions.yandexcloud.net/d4eq4i3fov37r2ae1n7n",
} as const;