openapi: 3.0.0
info:
  title: AuxChat API
  version: 1.0.0

paths:
  /add-energy:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e10cfpm08ikk1k5mp4
        service_account_id: ajekuudp0ggenbgn2gdt

  /generate-upload-url:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e1drhlub4imqleg10q

  /create-payment:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e1gbggnqgt6lrsh9n7

  /payment-webhook:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e235nr619fsgkt1qvi

  /get-messages:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e25ugin6o29hr4ots8

  /login:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eae7r2eq6bt0ucrv35

  /get-subscriptions:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eaga56qmoe21os17od

  /get-conversations:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ebuvvtbpqd5f09070g

  /create-user:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4egbht42po268s1q56a

  /verify-sms:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4egj9hb0n3psc0eck02

  /reset-password:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ek1ma9nls3m5150jhb

  /add-reaction:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4elu8l3mmf6jpgbi581

  /profile-photos:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4emmve89ihd1nnfhcm9

  /blacklist:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4enost4267cmdl5cnfl

  /send-sms:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eq413fov37r2aeln7n

  /send-message:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eqjhv1ab66or71eli4

  /register:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4erd2o6kv7rjhsb9a9h

  /subscribe:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eruja65h9305n2l1ts

  /update-activity:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4es73t1cfkmee0kd724

  /private-messages:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4es8snba4ua5e0s6kgr

  /admin-users:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ev3dr7fqpjpd9p24ma

  /get-user:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ev53ggag7ku6bldvpj

x-yc-apigateway-cors:
  allowed-origins:
    - '*'
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - Content-Type
    - X-User-Id
    - X-Auth-Token
    - X-Session-Id
  max-age: 86400